# Generated by Django 4.2.1 on 2023-05-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_userregister_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="entry", name="authors",),
        migrations.RemoveField(model_name="entry", name="blog",),
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Blog",),
        migrations.DeleteModel(name="Entry",),
    ]
