# Generated by Django 4.2.1 on 2023-05-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_remove_entry_authors_remove_entry_blog_delete_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userregister", name="city",),
    ]
